version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build
          command: make

      - run:
          name: Test
          command: make test

      - run:
          name: Vet
          command: make vet

workflows:
  version: 2

  test:
    jobs:
      - build
